### ISSUE TITLE
C# Example

### ISSUE THREAD

**Issue by innoist** [mailchimp/APIv3-examples#1]
Can we have C# Wrapper just like we had for v2.0 (https://github.com/danesparza/MailChimp.NET)

**Comment by toomuchpete** [comment]
Hey @innoist,
So, that code you link is actually a wrapper rather than example code. We plan to have full wrappers for certain languages, as well as these examples. Also, that wrapper is written by a third party, and I'm not aware of any devs here at MailChimp that have experience with C#, so we'll probably leave creating examples or wrappers in C# to the community. I'd hate for us to produce bad examples that newer C# developers use to their detriment. 

That said, we'd love to have some support for C# developers, so any help in that direction would be greatly appreciated.
