### ISSUE TITLE
Email Update - PATCH

### ISSUE THREAD

**Issue by rwarr** [mailchimp/APIv3-examples#17]
Having trouble trying to update the email. Is there something special I should be putting into the body? 2.0 api was way easier updating the email field.

Using Node JS. I can update the status field but not email_address for some odd reason.

Code:

var options = {
        baseUrl: 'https://us9.api.mailchimp.com',
        uri: '/3.0/lists/listid/members/insertmemberid',
        method: 'PATCH',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'apikey insertapikey'
        },
        body: {
            'email_address': 'mooness@moo.com',
            'status': 'subscribed'
        },
        json: true
    };

**Comment by toomuchpete** [comment]
Hi @rwarr -- unfortunately, we won't be able to provide API support in this repository. For support in the future, please email apihelp at mailchimp dot com.

To save you a step this time, though: we don't support email updates in API v3. They're not well-supported in app (it functions almost identically to a delete and subscribe) so that's the method we recommend for API v3.
