### ISSUE TITLE
ASP.NET PATCH

### ISSUE THREAD

**Issue by andyb82** [mailchimp/APIv3-examples#19]
I am trying to get http 'PATCH' working on mailchimp API 3 using ASP.NET. I have no problem with 'GET' and 'POST'.

I can get a 'PATCH' call to be accepted by the API but the data does change. The same call using the API playground does change the data.

I see from a previous issue that mailchimp do not have any .net developers, so to help in this issue I would like mailchimp to add some test calls to the api to allow developers to get their interface working. For instance, the test 'PATCH' call would send some fixed json to the mailchimp server and if the data is correct the server returns a 200 status code with a suitable json message. If the data is incorrect the server should return a suitable error message.

Note: to use 'PATCH' in asp.net you require .net 4.5+. Also using the restSharp dll allows you do the 'PATCH' call in a few lines of code.

Thanks.

**Comment by toomuchpete** [comment]
@andyb82 One thing to check, we've found that a lot of .NET users have problems because many of the .NET HTTP libraries send the `Expect: 100-Continue` header, and Akamai doesn't support that for PATCH operations. To check to see if that is the issue you're having, you can tunnel a PATCH request through a POST request using the `X-HTTP-Method-Override` header.

**Comment by andyb82** [comment]
Would your server return a 200 status code if the Expect: 100-continue header was present in a PATCH request?

I tried: System.Net.ServicePointManager.Expect100Continue = false;
but this made no difference.

**Comment by toomuchpete** [comment]
Gotcha. Sounds like this is a question for support then. Please send an email to apihelp@mailchimp.com and they should be able to help you out. Thanks!
